version: '3.8'
services:
  app:
    build: .
    container_name: afiliaciones_app
    ports:
      - "3000:3000"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    env_file:
      - .env.development
  redis:
    image: redis:7.2
    container_name: afiliaciones_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
